### ISSUE TITLE
command line interface

### ISSUE THREAD

**Issue by couleurm** [CaptainFallaway/DiscordRoleSheeter#1]
hey, it'd be cool to have a watcher script that automatically pushes the recently saved file automatically, does that sound possible?

**Comment by CaptainFallaway** [comment]
It could be something that I can implement in the app itself running in the event loop as a trampoline task and some option button for it. 

But it kind of goes against my motive of the little window previewing what changes that have been made, since I want the user to verify their changes so that there are no mistakes.

But what do you think it?
